---
title: "glms for proportion abscised"
author: "E.E. Jackson"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: pdf_document 
---

```{r, message=FALSE, warning=FALSE}
rm(list = ls())
require(tidyverse)
require(lme4)
library(knitr)
library(report)
require(MuMIn)
require(ggpubr)
require(MASS)
theme_set(theme_pubr(base_size = 15))
opts_chunk$set(tidy.opts=list(width.cutoff=50),tidy=TRUE)
```
## Read dataset 

```{r}
fruitDat <- read.csv("../output/tables/cleanData.csv")
dm <- read.csv("../output/tables/dispersalMode.csv")
fruitDatFull <- read.csv("../output/tables/fullCleanData.csv")

fruitDat %>%
	mutate(seedpred_pres = factor(ifelse(seedpred_pres == 0, "No", "Yes"))) %>%
	left_join(dplyr::select(dm, dispersal_mode = bio, sp), by = "sp") -> fruitDat

fruitDatFull %>%
	mutate(seedpred_pres = factor(ifelse(seedpred_pres == 0, "No", "Yes"))) %>%
	left_join(dplyr::select(dm, dispersal_mode = bio, sp), by = "sp") -> fruitDatFull
```
## mixed effect models

```{r, message=TRUE, warning=TRUE}
#model <- lmer(cbind(abscised_seeds,viable_seeds)~seedpred_pres + (1|sp),quasibinomial,data=fruitDat)

#Error in if (REML) p else 0L : argument is not interpretable as logical

# doesn't like lmer, change to glmer

#model <- glmer(cbind(abscised_seeds,viable_seeds)~seedpred_pres + (1|sp),quasibinomial,data=fruitDat)

#Error in lme4::glFormula(formula = cbind(abscised_seeds, viable_seeds) ~  :          "quasi" families cannot be used in glmer   

# doesn't like quasibinomial, change to binomial

model1 <- glmer(cbind(abscised_seeds,viable_seeds)~seedpred_pres + (1|sp),binomial,data=fruitDat)
summary(model1)

# cbind does work! lets see if there's a difference in the summary output

model2 <- glmer(proportion_abscised~seedpred_pres + (1|sp),binomial,data=fruitDat, weights=total_seeds)
summary(model2)

# try year as random effect

model3 <- glmer(cbind(abscised_seeds,viable_seeds)~seedpred_pres + (year|sp),binomial(logit),data=fruitDatFull)

r.squaredGLMM(model1) # calcluate R squared for the cbind model

# marginal R squared (fixed effects alone) is 0.02
# conditional R squared is 0.44

# I found out that although lme4 won't let us fit quasi-likelihoods, MASS will.
# I don't know if this is better or not but it allows year as a random effect
model4 <- MASS::glmmPQL(cbind(abscised_seeds,viable_seeds) ~ seedpred_pres, random = ~ 1 | sp, family=quasibinomial, data=fruitDat)
summary(model4)

model5 <- MASS::glmmPQL(cbind(abscised_seeds,viable_seeds) ~ seedpred_pres, random = ~ 1 | year/sp, family=quasibinomial, data=fruitDatFull)
summary(model5)


```
## Check seedpred pres

```{r, fig_width=6, fig_height=4}
# a plot using the dataset with NAs removed
fruitDat.noNA <- fruitDat[complete.cases(fruitDat), ]

ggplot(fruitDat.noNA, aes(y=proportion_abscised, group=seedpred_pres, x=seedpred_pres)) + 
	geom_boxplot(alpha= 0.8,position = position_dodge2(preserve = "single"), width=0.4, size=1)+
	geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.5, size=2) +
	ylab("Proportion of seeds abscised") +
	xlab("Presence of seed predator")

# plot with fulldataset 
ggplot(fruitDat, aes(y=proportion_abscised, group=seedpred_pres, x=seedpred_pres)) + 
	geom_boxplot(alpha= 0.8,position = position_dodge2(preserve = "single"), width=0.4, size=1)+
	geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.5, size=2) +
	ylab("Proportion of seeds abscised") +
	xlab("Presence of seed predator")

# presence of seed predators corresponds to a higher proportion of abscised seeds in both the full dataset and the na's removed dataset
```
## observation-level random effects
```{r}
m1 <- glmer(cbind(abscised_seeds,viable_seeds)~seedpred_pres + (1|sp), binomial(logit), data = fruitDat)

#Create a sequence of numbers corresponding to each observation (rows of the dataframe)
obs<-seq(nrow(fruitDat))

#Fit the model
m1obs<-glmer(cbind(abscised_seeds,viable_seeds)~seedpred_pres + (1|sp) + (1|obs),binomial(logit),data=fruitDat)
m1obs #Std Dev of Obs level random effect should be ~ 0.5 in this example

```

```{r}
m1 <- glmer(cbind(abscised_seeds,viable_seeds) ~ seedpred_pres + (1|sp),family=binomial(logit), data=fruitDat)

overdisp_fun <- function(model) {
    rdf <- df.residual(model)
    rp <- residuals(model,type="pearson")
    Pearson.chisq <- sum(rp^2)
    prat <- Pearson.chisq/rdf
    pval <- pchisq(Pearson.chisq, df=rdf, lower.tail=FALSE)
    c(chisq=Pearson.chisq,ratio=prat,rdf=rdf,p=pval)
}
overdisp_fun(m1)
#ratio is not greater than 1

#rescale and centre continuous variables
numcols <- grep("^c\\.",names(fruitDatFull))
dfs <- fruitDatFull
dfs[,numcols] <- scale(dfs[,numcols])
m1_sc <- update(model3,data=dfs)

#check for singularity
tt <- getME(m1_sc,"theta")
ll <- getME(m1_sc,"lower")
min(tt[ll==0])

ss <- getME(m1_sc,c("theta","fixef"))
m2 <- update(m1_sc,start=ss,control=glmerControl(optCtrl=list(maxfun=2e4)))

aa <- lme4::allFit(m2)
summary(aa)

is.OK <- sapply(aa,is,"merMod")  ## nlopt NELDERMEAD failed, others succeeded
aa.OK <- aa[is.OK]
lapply(aa.OK,function(x) x@optinfo$conv$lme4$messages)

m <- glmer(cbind(abscised_seeds,viable_seeds)~seedpred_pres + log10(seed_dry) * height_avg * cvseed + (year|sp), binomial(logit),data=fruitDatFull)

```