---
title: "glms for proportion abscised"
author: "E.E. Jackson"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: pdf_document 
---

```{r, message=FALSE, warning=FALSE}
rm(list = ls())
require(tidyverse)
require(lme4)
library(knitr)
library(report)
opts_chunk$set(tidy.opts=list(width.cutoff=50),tidy=TRUE)
```
## Read dataset 

```{r}

fruitDat <- read.csv("../output/tables/cleanData.csv")
dm <- read.csv("../output/tables/dispersalMode.csv")

```

## generalized linear models

```{r}
# make sure that predator presence is a factor and add dispersal mode
fruitDat %>%
	mutate(seedpred_pres = factor(ifelse(seedpred_pres == 0, "No", "Yes"))) %>%
	left_join(select(dm, dispersal_mode = bio, sp), by = "sp") -> fruitDat

## maximal model ##

fullmod <- 
glm(cbind(abscised_seeds,viable_seeds) ~ seedpred_pres + log10(seed_dry) * height_avg + cvseed + log10(cofruit) + bcireproductive + endocarp_investment + dispersal_mode, data = na.omit(fruitDat), family = quasibinomial(link = logit))

summary(fullmod)

anova(fullmod,test="F")

```