---
title: "Testing for temporal autocorrelation in fruit abscission"
author: "E.E. Jackson"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: pdf_document 
---

```{r, message=FALSE, warning=FALSE}
rm(list = ls())
require(tidyverse)
library(knitr)
require(patchwork)
require(ggpubr)
require(DHARMa)
require(lme4)
require(forecast)
require(lubridate)
opts_chunk$set(tidy.opts=list(width.cutoff=50),tidy=TRUE,cache.lazy = FALSE,cache = TRUE)
```

```{r, message=TRUE, warning=TRUE}

fruitDatFull <- read.csv("../output/tables/fullCleanData.csv")

fruitDatFull %>%
	mutate(seedpred_pres = factor(ifelse(seedpred_pres == 0, "No", "Yes"))) -> fruitDatFull

fruitDatFull$seed_dry_log <- log10(fruitDatFull$seed_dry)
fruitDatFull$cofruit_log <- log10(fruitDatFull$cofruit)
fruitDatFull$bcireproductive_log <- log10(fruitDatFull$bcireproductive)
#round these to integers so that DHARMa will take them
fruitDatFull$abscised_seeds <- round(fruitDatFull$abscised_seeds)
fruitDatFull$viable_seeds <- round(fruitDatFull$viable_seeds)

fruitDatFull$year <- as.character(fruitDatFull$year)
fruitDatFull$year <- lubridate::ymd(fruitDatFull$year, truncated = 2L)

set.seed(123)
```

## Testing for temporal autocorrelation
Autocorrelations or lagged correlations are used to assess whether a time series is dependent on its past

```{r, message=TRUE, warning=TRUE,fig_width=6, fig_height=4}

df<-select(fruitDatFull, c("year","abscised_seeds","viable_seeds", "sp"))

fittedModel <- lme4::glmer(cbind(abscised_seeds,viable_seeds) ~ (1|sp), data = df, family = binomial(logit) )

df$res <- residuals(fittedModel)

# max lag should be 31
df %>%
    count(sp) %>%
    filter(n == max(n) )

# order the dataset by time 
df <- df %>%
     arrange(sp, year)

# fill in the blanks
dat_expand <- df %>%
    group_by(sp) %>%
    complete(year = 1988:2018)


#calculate and plot the residual autocorrelation function
acf.df<-acf(dat_expand$res, lag.max = 31, na.action = na.pass, ci = 0)

simulationOutput <- simulateResiduals(fittedModel = fittedModel)

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = fruitDatFull$year)
```